// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(speakrs_ffiFFI)
import speakrs_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_speakrs_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_speakrs_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureSpeakrsFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles.
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol PreparedModelsHandleProtocol: AnyObject, Sendable {

    func modelDir()  -> String

    func modelRevision()  -> String

}
open class PreparedModelsHandle: PreparedModelsHandleProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_speakrs_ffi_fn_clone_preparedmodelshandle(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_speakrs_ffi_fn_free_preparedmodelshandle(handle, $0) }
    }




open func modelDir() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_method_preparedmodelshandle_model_dir(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

open func modelRevision() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_method_preparedmodelshandle_model_revision(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}



}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePreparedModelsHandle: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = PreparedModelsHandle

    public static func lift(_ handle: UInt64) throws -> PreparedModelsHandle {
        return PreparedModelsHandle(unsafeFromHandle: handle)
    }

    public static func lower(_ value: PreparedModelsHandle) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PreparedModelsHandle {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: PreparedModelsHandle, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePreparedModelsHandle_lift(_ handle: UInt64) throws -> PreparedModelsHandle {
    return try FfiConverterTypePreparedModelsHandle.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePreparedModelsHandle_lower(_ value: PreparedModelsHandle) -> UInt64 {
    return FfiConverterTypePreparedModelsHandle.lower(value)
}






public protocol SpeakrsCancelTokenProtocol: AnyObject, Sendable {

    func cancel()

    func isCancelled()  -> Bool

}
open class SpeakrsCancelToken: SpeakrsCancelTokenProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_speakrs_ffi_fn_clone_speakrscanceltoken(self.handle, $0) }
    }
public convenience init() {
    let handle =
        try! rustCall() {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_constructor_speakrscanceltoken_new(uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_speakrs_ffi_fn_free_speakrscanceltoken(handle, $0) }
    }




open func cancel()  {try! rustCall() {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_method_speakrscanceltoken_cancel(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}

open func isCancelled() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_method_speakrscanceltoken_is_cancelled(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}



}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSpeakrsCancelToken: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SpeakrsCancelToken

    public static func lift(_ handle: UInt64) throws -> SpeakrsCancelToken {
        return SpeakrsCancelToken(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SpeakrsCancelToken) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SpeakrsCancelToken {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SpeakrsCancelToken, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpeakrsCancelToken_lift(_ handle: UInt64) throws -> SpeakrsCancelToken {
    return try FfiConverterTypeSpeakrsCancelToken.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpeakrsCancelToken_lower(_ value: SpeakrsCancelToken) -> UInt64 {
    return FfiConverterTypeSpeakrsCancelToken.lower(value)
}






public protocol SpeakrsPipelineProtocol: AnyObject, Sendable {

    func diarizeFile(path: String, fileId: String, pipelineConfig: PipelineConfig?, cancelToken: SpeakrsCancelToken?) throws  -> DiarizationResult

    func diarizeSamples(samples: [Float], fileId: String, pipelineConfig: PipelineConfig?, cancelToken: SpeakrsCancelToken?) throws  -> DiarizationResult

    func intoQueue(pipelineConfig: PipelineConfig?) throws  -> SpeakrsQueue

}
open class SpeakrsPipeline: SpeakrsPipelineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_speakrs_ffi_fn_clone_speakrspipeline(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_speakrs_ffi_fn_free_speakrspipeline(handle, $0) }
    }


public static func fromPrepared(prepared: PreparedModelsHandle, mode: ExecutionMode, pipelineConfig: PipelineConfig?, runtimeConfig: RuntimeConfig?)throws  -> SpeakrsPipeline  {
    return try  FfiConverterTypeSpeakrsPipeline_lift(try rustCallWithError(FfiConverterTypeSpeakrsError_lift) {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_constructor_speakrspipeline_from_prepared(
        FfiConverterTypePreparedModelsHandle_lower(prepared),
        FfiConverterTypeExecutionMode_lower(mode),
        FfiConverterOptionTypePipelineConfig.lower(pipelineConfig),
        FfiConverterOptionTypeRuntimeConfig.lower(runtimeConfig),uniffiCallStatus
    )
})
}



open func diarizeFile(path: String, fileId: String, pipelineConfig: PipelineConfig?, cancelToken: SpeakrsCancelToken?)throws  -> DiarizationResult  {
    return try  FfiConverterTypeDiarizationResult_lift(try rustCallWithError(FfiConverterTypeSpeakrsError_lift) {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_method_speakrspipeline_diarize_file(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),
        FfiConverterString.lower(fileId),
        FfiConverterOptionTypePipelineConfig.lower(pipelineConfig),
        FfiConverterOptionTypeSpeakrsCancelToken.lower(cancelToken),uniffiCallStatus
    )
})
}

open func diarizeSamples(samples: [Float], fileId: String, pipelineConfig: PipelineConfig?, cancelToken: SpeakrsCancelToken?)throws  -> DiarizationResult  {
    return try  FfiConverterTypeDiarizationResult_lift(try rustCallWithError(FfiConverterTypeSpeakrsError_lift) {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_method_speakrspipeline_diarize_samples(
            self.uniffiCloneHandle(),
        FfiConverterSequenceFloat.lower(samples),
        FfiConverterString.lower(fileId),
        FfiConverterOptionTypePipelineConfig.lower(pipelineConfig),
        FfiConverterOptionTypeSpeakrsCancelToken.lower(cancelToken),uniffiCallStatus
    )
})
}

open func intoQueue(pipelineConfig: PipelineConfig?)throws  -> SpeakrsQueue  {
    return try  FfiConverterTypeSpeakrsQueue_lift(try rustCallWithError(FfiConverterTypeSpeakrsError_lift) {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_method_speakrspipeline_into_queue(
            self.uniffiCloneHandle(),
        FfiConverterOptionTypePipelineConfig.lower(pipelineConfig),uniffiCallStatus
    )
})
}



}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSpeakrsPipeline: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SpeakrsPipeline

    public static func lift(_ handle: UInt64) throws -> SpeakrsPipeline {
        return SpeakrsPipeline(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SpeakrsPipeline) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SpeakrsPipeline {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SpeakrsPipeline, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpeakrsPipeline_lift(_ handle: UInt64) throws -> SpeakrsPipeline {
    return try FfiConverterTypeSpeakrsPipeline.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpeakrsPipeline_lower(_ value: SpeakrsPipeline) -> UInt64 {
    return FfiConverterTypeSpeakrsPipeline.lower(value)
}






public protocol SpeakrsQueueProtocol: AnyObject, Sendable {

    func pushFile(fileId: String, path: String) throws  -> UInt64

    func pushSamples(fileId: String, samples: [Float]) throws  -> UInt64

    func recv() throws  -> QueueResult

    func tryRecv() throws  -> QueueResult?

}
open class SpeakrsQueue: SpeakrsQueueProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_speakrs_ffi_fn_clone_speakrsqueue(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_speakrs_ffi_fn_free_speakrsqueue(handle, $0) }
    }




open func pushFile(fileId: String, path: String)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeSpeakrsError_lift) {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_method_speakrsqueue_push_file(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(fileId),
        FfiConverterString.lower(path),uniffiCallStatus
    )
})
}

open func pushSamples(fileId: String, samples: [Float])throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeSpeakrsError_lift) {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_method_speakrsqueue_push_samples(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(fileId),
        FfiConverterSequenceFloat.lower(samples),uniffiCallStatus
    )
})
}

open func recv()throws  -> QueueResult  {
    return try  FfiConverterTypeQueueResult_lift(try rustCallWithError(FfiConverterTypeSpeakrsError_lift) {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_method_speakrsqueue_recv(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

open func tryRecv()throws  -> QueueResult?  {
    return try  FfiConverterOptionTypeQueueResult.lift(try rustCallWithError(FfiConverterTypeSpeakrsError_lift) {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_method_speakrsqueue_try_recv(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}



}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSpeakrsQueue: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SpeakrsQueue

    public static func lift(_ handle: UInt64) throws -> SpeakrsQueue {
        return SpeakrsQueue(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SpeakrsQueue) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SpeakrsQueue {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SpeakrsQueue, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpeakrsQueue_lift(_ handle: UInt64) throws -> SpeakrsQueue {
    return try FfiConverterTypeSpeakrsQueue.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpeakrsQueue_lower(_ value: SpeakrsQueue) -> UInt64 {
    return FfiConverterTypeSpeakrsQueue.lower(value)
}




public struct AhcConfig: Equatable, Hashable {
    public var threshold: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(threshold: Float) {
        self.threshold = threshold
    }




}

#if compiler(>=6)
extension AhcConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAhcConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AhcConfig {
        return
            try AhcConfig(
                threshold: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: AhcConfig, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.threshold, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAhcConfig_lift(_ buf: RustBuffer) throws -> AhcConfig {
    return try FfiConverterTypeAhcConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAhcConfig_lower(_ value: AhcConfig) -> RustBuffer {
    return FfiConverterTypeAhcConfig.lower(value)
}


public struct BinarizeConfig: Equatable, Hashable {
    public var onset: Float
    public var offset: Float
    public var minDurationOn: UInt64
    public var minDurationOff: UInt64
    public var padOnset: UInt64
    public var padOffset: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(onset: Float, offset: Float, minDurationOn: UInt64, minDurationOff: UInt64, padOnset: UInt64, padOffset: UInt64) {
        self.onset = onset
        self.offset = offset
        self.minDurationOn = minDurationOn
        self.minDurationOff = minDurationOff
        self.padOnset = padOnset
        self.padOffset = padOffset
    }




}

#if compiler(>=6)
extension BinarizeConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBinarizeConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BinarizeConfig {
        return
            try BinarizeConfig(
                onset: FfiConverterFloat.read(from: &buf),
                offset: FfiConverterFloat.read(from: &buf),
                minDurationOn: FfiConverterUInt64.read(from: &buf),
                minDurationOff: FfiConverterUInt64.read(from: &buf),
                padOnset: FfiConverterUInt64.read(from: &buf),
                padOffset: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: BinarizeConfig, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.onset, into: &buf)
        FfiConverterFloat.write(value.offset, into: &buf)
        FfiConverterUInt64.write(value.minDurationOn, into: &buf)
        FfiConverterUInt64.write(value.minDurationOff, into: &buf)
        FfiConverterUInt64.write(value.padOnset, into: &buf)
        FfiConverterUInt64.write(value.padOffset, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBinarizeConfig_lift(_ buf: RustBuffer) throws -> BinarizeConfig {
    return try FfiConverterTypeBinarizeConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBinarizeConfig_lower(_ value: BinarizeConfig) -> RustBuffer {
    return FfiConverterTypeBinarizeConfig.lower(value)
}


public struct DiarizationResult: Equatable, Hashable {
    public var segments: [Segment]
    public var rttm: String
    public var duration: Double
    public var mode: ExecutionMode
    public var modelRevision: String
    public var timing: TimingStats

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(segments: [Segment], rttm: String, duration: Double, mode: ExecutionMode, modelRevision: String, timing: TimingStats) {
        self.segments = segments
        self.rttm = rttm
        self.duration = duration
        self.mode = mode
        self.modelRevision = modelRevision
        self.timing = timing
    }




}

#if compiler(>=6)
extension DiarizationResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDiarizationResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DiarizationResult {
        return
            try DiarizationResult(
                segments: FfiConverterSequenceTypeSegment.read(from: &buf),
                rttm: FfiConverterString.read(from: &buf),
                duration: FfiConverterDouble.read(from: &buf),
                mode: FfiConverterTypeExecutionMode.read(from: &buf),
                modelRevision: FfiConverterString.read(from: &buf),
                timing: FfiConverterTypeTimingStats.read(from: &buf)
        )
    }

    public static func write(_ value: DiarizationResult, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeSegment.write(value.segments, into: &buf)
        FfiConverterString.write(value.rttm, into: &buf)
        FfiConverterDouble.write(value.duration, into: &buf)
        FfiConverterTypeExecutionMode.write(value.mode, into: &buf)
        FfiConverterString.write(value.modelRevision, into: &buf)
        FfiConverterTypeTimingStats.write(value.timing, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDiarizationResult_lift(_ buf: RustBuffer) throws -> DiarizationResult {
    return try FfiConverterTypeDiarizationResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDiarizationResult_lower(_ value: DiarizationResult) -> RustBuffer {
    return FfiConverterTypeDiarizationResult.lower(value)
}


public struct ErrorInfo: Equatable, Hashable {
    public var category: String
    public var code: String
    public var message: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(category: String, code: String, message: String) {
        self.category = category
        self.code = code
        self.message = message
    }




}

#if compiler(>=6)
extension ErrorInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeErrorInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ErrorInfo {
        return
            try ErrorInfo(
                category: FfiConverterString.read(from: &buf),
                code: FfiConverterString.read(from: &buf),
                message: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ErrorInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.category, into: &buf)
        FfiConverterString.write(value.code, into: &buf)
        FfiConverterString.write(value.message, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeErrorInfo_lift(_ buf: RustBuffer) throws -> ErrorInfo {
    return try FfiConverterTypeErrorInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeErrorInfo_lower(_ value: ErrorInfo) -> RustBuffer {
    return FfiConverterTypeErrorInfo.lower(value)
}


public struct PipelineConfig: Equatable, Hashable {
    public var binarize: BinarizeConfig
    public var ahc: AhcConfig
    public var vbx: VbxConfig
    public var mergeGap: Double
    public var speakerKeepThreshold: Double
    public var reconstructMethod: ReconstructMethod
    public var reconstructEpsilon: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(binarize: BinarizeConfig, ahc: AhcConfig, vbx: VbxConfig, mergeGap: Double, speakerKeepThreshold: Double, reconstructMethod: ReconstructMethod, reconstructEpsilon: Float) {
        self.binarize = binarize
        self.ahc = ahc
        self.vbx = vbx
        self.mergeGap = mergeGap
        self.speakerKeepThreshold = speakerKeepThreshold
        self.reconstructMethod = reconstructMethod
        self.reconstructEpsilon = reconstructEpsilon
    }




}

#if compiler(>=6)
extension PipelineConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePipelineConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PipelineConfig {
        return
            try PipelineConfig(
                binarize: FfiConverterTypeBinarizeConfig.read(from: &buf),
                ahc: FfiConverterTypeAhcConfig.read(from: &buf),
                vbx: FfiConverterTypeVbxConfig.read(from: &buf),
                mergeGap: FfiConverterDouble.read(from: &buf),
                speakerKeepThreshold: FfiConverterDouble.read(from: &buf),
                reconstructMethod: FfiConverterTypeReconstructMethod.read(from: &buf),
                reconstructEpsilon: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: PipelineConfig, into buf: inout [UInt8]) {
        FfiConverterTypeBinarizeConfig.write(value.binarize, into: &buf)
        FfiConverterTypeAhcConfig.write(value.ahc, into: &buf)
        FfiConverterTypeVbxConfig.write(value.vbx, into: &buf)
        FfiConverterDouble.write(value.mergeGap, into: &buf)
        FfiConverterDouble.write(value.speakerKeepThreshold, into: &buf)
        FfiConverterTypeReconstructMethod.write(value.reconstructMethod, into: &buf)
        FfiConverterFloat.write(value.reconstructEpsilon, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePipelineConfig_lift(_ buf: RustBuffer) throws -> PipelineConfig {
    return try FfiConverterTypePipelineConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePipelineConfig_lower(_ value: PipelineConfig) -> RustBuffer {
    return FfiConverterTypePipelineConfig.lower(value)
}


public struct QueueResult: Equatable, Hashable {
    public var jobId: UInt64
    public var fileId: String
    public var result: DiarizationResult?
    public var error: ErrorInfo?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(jobId: UInt64, fileId: String, result: DiarizationResult?, error: ErrorInfo?) {
        self.jobId = jobId
        self.fileId = fileId
        self.result = result
        self.error = error
    }




}

#if compiler(>=6)
extension QueueResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeQueueResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> QueueResult {
        return
            try QueueResult(
                jobId: FfiConverterUInt64.read(from: &buf),
                fileId: FfiConverterString.read(from: &buf),
                result: FfiConverterOptionTypeDiarizationResult.read(from: &buf),
                error: FfiConverterOptionTypeErrorInfo.read(from: &buf)
        )
    }

    public static func write(_ value: QueueResult, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.jobId, into: &buf)
        FfiConverterString.write(value.fileId, into: &buf)
        FfiConverterOptionTypeDiarizationResult.write(value.result, into: &buf)
        FfiConverterOptionTypeErrorInfo.write(value.error, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQueueResult_lift(_ buf: RustBuffer) throws -> QueueResult {
    return try FfiConverterTypeQueueResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQueueResult_lower(_ value: QueueResult) -> RustBuffer {
    return FfiConverterTypeQueueResult.lower(value)
}


public struct RuntimeConfig: Equatable, Hashable {
    public var chunkEmbWorkers: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(chunkEmbWorkers: UInt64) {
        self.chunkEmbWorkers = chunkEmbWorkers
    }




}

#if compiler(>=6)
extension RuntimeConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRuntimeConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RuntimeConfig {
        return
            try RuntimeConfig(
                chunkEmbWorkers: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: RuntimeConfig, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.chunkEmbWorkers, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRuntimeConfig_lift(_ buf: RustBuffer) throws -> RuntimeConfig {
    return try FfiConverterTypeRuntimeConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRuntimeConfig_lower(_ value: RuntimeConfig) -> RustBuffer {
    return FfiConverterTypeRuntimeConfig.lower(value)
}


public struct Segment: Equatable, Hashable {
    public var start: Double
    public var end: Double
    public var speaker: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(start: Double, end: Double, speaker: String) {
        self.start = start
        self.end = end
        self.speaker = speaker
    }




}

#if compiler(>=6)
extension Segment: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSegment: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Segment {
        return
            try Segment(
                start: FfiConverterDouble.read(from: &buf),
                end: FfiConverterDouble.read(from: &buf),
                speaker: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Segment, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.start, into: &buf)
        FfiConverterDouble.write(value.end, into: &buf)
        FfiConverterString.write(value.speaker, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSegment_lift(_ buf: RustBuffer) throws -> Segment {
    return try FfiConverterTypeSegment.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSegment_lower(_ value: Segment) -> RustBuffer {
    return FfiConverterTypeSegment.lower(value)
}


public struct TimingStats: Equatable, Hashable {
    public var modelPrepareMs: UInt64
    public var audioDecodeMs: UInt64
    public var audioResampleMs: UInt64
    public var pipelineMs: UInt64
    public var queueWaitMs: UInt64
    public var totalMs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(modelPrepareMs: UInt64, audioDecodeMs: UInt64, audioResampleMs: UInt64, pipelineMs: UInt64, queueWaitMs: UInt64, totalMs: UInt64) {
        self.modelPrepareMs = modelPrepareMs
        self.audioDecodeMs = audioDecodeMs
        self.audioResampleMs = audioResampleMs
        self.pipelineMs = pipelineMs
        self.queueWaitMs = queueWaitMs
        self.totalMs = totalMs
    }




}

#if compiler(>=6)
extension TimingStats: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTimingStats: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TimingStats {
        return
            try TimingStats(
                modelPrepareMs: FfiConverterUInt64.read(from: &buf),
                audioDecodeMs: FfiConverterUInt64.read(from: &buf),
                audioResampleMs: FfiConverterUInt64.read(from: &buf),
                pipelineMs: FfiConverterUInt64.read(from: &buf),
                queueWaitMs: FfiConverterUInt64.read(from: &buf),
                totalMs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: TimingStats, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.modelPrepareMs, into: &buf)
        FfiConverterUInt64.write(value.audioDecodeMs, into: &buf)
        FfiConverterUInt64.write(value.audioResampleMs, into: &buf)
        FfiConverterUInt64.write(value.pipelineMs, into: &buf)
        FfiConverterUInt64.write(value.queueWaitMs, into: &buf)
        FfiConverterUInt64.write(value.totalMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimingStats_lift(_ buf: RustBuffer) throws -> TimingStats {
    return try FfiConverterTypeTimingStats.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimingStats_lower(_ value: TimingStats) -> RustBuffer {
    return FfiConverterTypeTimingStats.lower(value)
}


public struct VbxConfig: Equatable, Hashable {
    public var fa: Double
    public var fb: Double
    public var maxIters: UInt64
    public var epsilon: Double
    public var initSmoothing: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(fa: Double, fb: Double, maxIters: UInt64, epsilon: Double, initSmoothing: Double) {
        self.fa = fa
        self.fb = fb
        self.maxIters = maxIters
        self.epsilon = epsilon
        self.initSmoothing = initSmoothing
    }




}

#if compiler(>=6)
extension VbxConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVbxConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VbxConfig {
        return
            try VbxConfig(
                fa: FfiConverterDouble.read(from: &buf),
                fb: FfiConverterDouble.read(from: &buf),
                maxIters: FfiConverterUInt64.read(from: &buf),
                epsilon: FfiConverterDouble.read(from: &buf),
                initSmoothing: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: VbxConfig, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.fa, into: &buf)
        FfiConverterDouble.write(value.fb, into: &buf)
        FfiConverterUInt64.write(value.maxIters, into: &buf)
        FfiConverterDouble.write(value.epsilon, into: &buf)
        FfiConverterDouble.write(value.initSmoothing, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVbxConfig_lift(_ buf: RustBuffer) throws -> VbxConfig {
    return try FfiConverterTypeVbxConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVbxConfig_lower(_ value: VbxConfig) -> RustBuffer {
    return FfiConverterTypeVbxConfig.lower(value)
}



public enum ExecutionMode: Equatable, Hashable {

    case cpu
    case coreMl
    case coreMlFast
    case cuda
    case cudaFast
    case miGraphX





}

#if compiler(>=6)
extension ExecutionMode: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeExecutionMode: FfiConverterRustBuffer {
    typealias SwiftType = ExecutionMode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ExecutionMode {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .cpu

        case 2: return .coreMl

        case 3: return .coreMlFast

        case 4: return .cuda

        case 5: return .cudaFast

        case 6: return .miGraphX

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ExecutionMode, into buf: inout [UInt8]) {
        switch value {


        case .cpu:
            writeInt(&buf, Int32(1))


        case .coreMl:
            writeInt(&buf, Int32(2))


        case .coreMlFast:
            writeInt(&buf, Int32(3))


        case .cuda:
            writeInt(&buf, Int32(4))


        case .cudaFast:
            writeInt(&buf, Int32(5))


        case .miGraphX:
            writeInt(&buf, Int32(6))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExecutionMode_lift(_ buf: RustBuffer) throws -> ExecutionMode {
    return try FfiConverterTypeExecutionMode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExecutionMode_lower(_ value: ExecutionMode) -> RustBuffer {
    return FfiConverterTypeExecutionMode.lower(value)
}




public enum ReconstructMethod: Equatable, Hashable {

    case standard
    case smoothed





}

#if compiler(>=6)
extension ReconstructMethod: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeReconstructMethod: FfiConverterRustBuffer {
    typealias SwiftType = ReconstructMethod

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ReconstructMethod {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .standard

        case 2: return .smoothed

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ReconstructMethod, into buf: inout [UInt8]) {
        switch value {


        case .standard:
            writeInt(&buf, Int32(1))


        case .smoothed:
            writeInt(&buf, Int32(2))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReconstructMethod_lift(_ buf: RustBuffer) throws -> ReconstructMethod {
    return try FfiConverterTypeReconstructMethod.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReconstructMethod_lower(_ value: ReconstructMethod) -> RustBuffer {
    return FfiConverterTypeReconstructMethod.lower(value)
}



public
enum SpeakrsError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {



    case Failure(category: String, code: String, details: String
    )






    public var errorDescription: String? {
        String(reflecting: self)
    }

}

#if compiler(>=6)
extension SpeakrsError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSpeakrsError: FfiConverterRustBuffer {
    typealias SwiftType = SpeakrsError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SpeakrsError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .Failure(
            category: try FfiConverterString.read(from: &buf),
            code: try FfiConverterString.read(from: &buf),
            details: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SpeakrsError, into buf: inout [UInt8]) {
        switch value {





        case let .Failure(category,code,details):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(category, into: &buf)
            FfiConverterString.write(code, into: &buf)
            FfiConverterString.write(details, into: &buf)

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpeakrsError_lift(_ buf: RustBuffer) throws -> SpeakrsError {
    return try FfiConverterTypeSpeakrsError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpeakrsError_lower(_ value: SpeakrsError) -> RustBuffer {
    return FfiConverterTypeSpeakrsError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSpeakrsCancelToken: FfiConverterRustBuffer {
    typealias SwiftType = SpeakrsCancelToken?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSpeakrsCancelToken.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSpeakrsCancelToken.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeDiarizationResult: FfiConverterRustBuffer {
    typealias SwiftType = DiarizationResult?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeDiarizationResult.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeDiarizationResult.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeErrorInfo: FfiConverterRustBuffer {
    typealias SwiftType = ErrorInfo?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeErrorInfo.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeErrorInfo.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypePipelineConfig: FfiConverterRustBuffer {
    typealias SwiftType = PipelineConfig?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypePipelineConfig.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypePipelineConfig.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeQueueResult: FfiConverterRustBuffer {
    typealias SwiftType = QueueResult?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeQueueResult.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeQueueResult.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeRuntimeConfig: FfiConverterRustBuffer {
    typealias SwiftType = RuntimeConfig?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeRuntimeConfig.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeRuntimeConfig.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceFloat: FfiConverterRustBuffer {
    typealias SwiftType = [Float]

    public static func write(_ value: [Float], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterFloat.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Float] {
        let len: Int32 = try readInt(&buf)
        var seq = [Float]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterFloat.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSegment: FfiConverterRustBuffer {
    typealias SwiftType = [Segment]

    public static func write(_ value: [Segment], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSegment.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Segment] {
        let len: Int32 = try readInt(&buf)
        var seq = [Segment]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSegment.read(from: &buf))
        }
        return seq
    }
}
public func defaultCacheDir() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_func_default_cache_dir(uniffiCallStatus
    )
})
}
public func defaultModelRevision() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_func_default_model_revision(uniffiCallStatus
    )
})
}
public func defaultPipelineConfig(mode: ExecutionMode) -> PipelineConfig  {
    return try!  FfiConverterTypePipelineConfig_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_func_default_pipeline_config(
        FfiConverterTypeExecutionMode_lower(mode),uniffiCallStatus
    )
})
}
public func defaultRuntimeConfig() -> RuntimeConfig  {
    return try!  FfiConverterTypeRuntimeConfig_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_func_default_runtime_config(uniffiCallStatus
    )
})
}
public func prepareModels(mode: ExecutionMode, cacheDir: String?, modelDir: String?)throws  -> PreparedModelsHandle  {
    return try  FfiConverterTypePreparedModelsHandle_lift(try rustCallWithError(FfiConverterTypeSpeakrsError_lift) {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_func_prepare_models(
        FfiConverterTypeExecutionMode_lower(mode),
        FfiConverterOptionString.lower(cacheDir),
        FfiConverterOptionString.lower(modelDir),uniffiCallStatus
    )
})
}
public func requiredModelFilePaths(mode: ExecutionMode) -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_speakrs_ffi_fn_func_required_model_file_paths(
        FfiConverterTypeExecutionMode_lower(mode),uniffiCallStatus
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_speakrs_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_speakrs_ffi_checksum_func_default_cache_dir() != 51696) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_speakrs_ffi_checksum_func_default_model_revision() != 31982) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_speakrs_ffi_checksum_func_default_pipeline_config() != 45746) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_speakrs_ffi_checksum_func_default_runtime_config() != 55363) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_speakrs_ffi_checksum_func_prepare_models() != 31600) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_speakrs_ffi_checksum_func_required_model_file_paths() != 27167) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_speakrs_ffi_checksum_method_preparedmodelshandle_model_dir() != 50461) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_speakrs_ffi_checksum_method_preparedmodelshandle_model_revision() != 48439) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_speakrs_ffi_checksum_method_speakrscanceltoken_cancel() != 61441) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_speakrs_ffi_checksum_method_speakrscanceltoken_is_cancelled() != 54486) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_speakrs_ffi_checksum_method_speakrspipeline_diarize_file() != 54713) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_speakrs_ffi_checksum_method_speakrspipeline_diarize_samples() != 43886) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_speakrs_ffi_checksum_method_speakrspipeline_into_queue() != 58263) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_speakrs_ffi_checksum_method_speakrsqueue_push_file() != 13576) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_speakrs_ffi_checksum_method_speakrsqueue_push_samples() != 28581) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_speakrs_ffi_checksum_method_speakrsqueue_recv() != 65326) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_speakrs_ffi_checksum_method_speakrsqueue_try_recv() != 48303) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_speakrs_ffi_checksum_constructor_speakrscanceltoken_new() != 50506) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_speakrs_ffi_checksum_constructor_speakrspipeline_from_prepared() != 48252) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureSpeakrsFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all