name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  clippy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            features: cuda migraphx load-dynamic _metrics
          - os: macos-latest
            features: coreml cuda migraphx load-dynamic _metrics
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache Rust builds
        uses: Swatinem/rust-cache@v2
        with:
          cache-bin: false
          prefix-key: v1-rust

      - name: Run clippy
        run: cargo clippy --workspace --all-targets --features "${{ matrix.features }}" -- -D warnings

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            features: cuda migraphx load-dynamic _metrics
          - os: macos-latest
            features: coreml cuda migraphx load-dynamic _metrics
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust builds
        uses: Swatinem/rust-cache@v2
        with:
          cache-bin: false
          prefix-key: v1-rust

      - name: Compile tests
        run: cargo test --workspace --features "${{ matrix.features }}" --no-run
